# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-09-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20230925_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.TextField(default='', verbose_name=lists.models.List),
        ),
    ]
